### ISSUE TITLE
OSX NSTextField resize

### ISSUE THREAD

**Issue by wildthink** [alexdrone/FlexboxLayout#2]
I am trying to create an OS X Demo.
So far, I created an OS X framework target and a new DemoOSX. This can be found here
https://github.com/wildthink/FlexboxLayout

I'm trying to figure out how to get the NSTextField to resize to show all its text.

Any insight would be most appreciated.

**Comment by alexdrone** [comment]
Hello Jason!
I’ve fixed many issues with calculating the right measure for a view.
Could you try to see if it works with the stuff I just pushed?

**Comment by wildthink** [comment]
It's definitely better! The text field width now resizes. I'm still learning how to get Flexbox to do what I want. Is it easy/possible to get the a TextField to expand its height if the width isn't big enough?

I updated my fork (above) with the merges. It also has a FlexboxLayout-OSX framework target and DemoOSX app if want them.

Thanks!
